- name: Add hosts group temporary inventory group with pem path
  add_host:
    name: '{{ item.public_dns_name }}'
    groups: '{{ ec2_server_group_name }}'
    ansible_ssh_private_key_file: '{{ ec2_server_pem_path }}'
    ansible_ssh_user: '{{ ec2_server_ansible_ssh_user }}'
  with_items: "{{ ec2.instances }}"
  when: ec2_server_pem_path != ''

- name: Add hosts group temporary inventory group without pem path
  add_host:
    name: '{{ item.public_dns_name }}'
    groups: '{{ ec2_server_group_name }}'
    ansible_ssh_user: '{{ ec2_server_ansible_ssh_user }}'
  with_items: "{{ ec2.instances }}"
  when: ec2_server_pem_path == ''

