- name: Launch Instance
  ec2:
    group_id: '{{ firewall_rules.group_id }}'
    count: '{{ ec2_server_instcount }}'
    instance_type: '{{ ec2_server_instance_type }}'
    image: '{{ ec2_server_image }}'
    wait: true
    region: '{{ ec2_server_region }}'
    keypair: '{{ ec2_server_keypair }}'
    aws_access_key: '{{ ec2_server_access_key }}'
    aws_secret_key: '{{ ec2_server_secret_key }}'
    instance_tags:
      Name: '{{ ec2_server_name }}'
  register: ec2

- name: Instance Ids
  debug: msg="{{ ec2.instance_ids }}"
  

- name: Wait for SSH
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started

  with_items: "{{ ec2.instances }}"


